// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiOzieSslypm9ZM64OETHKwrMTUQvlFVQ',
    appId: '1:1009727907917:web:259683a334b4477260d404',
    messagingSenderId: '1009727907917',
    projectId: 'flutter-login-ef753',
    authDomain: 'flutter-login-ef753.firebaseapp.com',
    storageBucket: 'flutter-login-ef753.firebasestorage.app',
    measurementId: 'G-2G4LJXLV72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOLs861eTn-aIL88DHlRKzLG1YRCt8huE',
    appId: '1:1009727907917:android:3911b3463b08da5560d404',
    messagingSenderId: '1009727907917',
    projectId: 'flutter-login-ef753',
    storageBucket: 'flutter-login-ef753.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkz_7_W86xXI8_N9OKh9x_q3wkRXTHxMk',
    appId: '1:1009727907917:ios:84c2e9417892f9d460d404',
    messagingSenderId: '1009727907917',
    projectId: 'flutter-login-ef753',
    storageBucket: 'flutter-login-ef753.firebasestorage.app',
    iosBundleId: 'com.example.chessGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkz_7_W86xXI8_N9OKh9x_q3wkRXTHxMk',
    appId: '1:1009727907917:ios:84c2e9417892f9d460d404',
    messagingSenderId: '1009727907917',
    projectId: 'flutter-login-ef753',
    storageBucket: 'flutter-login-ef753.firebasestorage.app',
    iosBundleId: 'com.example.chessGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiOzieSslypm9ZM64OETHKwrMTUQvlFVQ',
    appId: '1:1009727907917:web:58679e8c4a43bf9560d404',
    messagingSenderId: '1009727907917',
    projectId: 'flutter-login-ef753',
    authDomain: 'flutter-login-ef753.firebaseapp.com',
    storageBucket: 'flutter-login-ef753.firebasestorage.app',
    measurementId: 'G-BR5HE5EJCJ',
  );
}
